// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8LZZcnm071RcMjcgIagPwcgiwF1eP_Hg',
    appId: '1:993398968251:web:307244e426f0b8cb0dbe9e',
    messagingSenderId: '993398968251',
    projectId: 'flutter-firebase-calenda-69514',
    authDomain: 'flutter-firebase-calenda-69514.firebaseapp.com',
    storageBucket: 'flutter-firebase-calenda-69514.firebasestorage.app',
    measurementId: 'G-V16BJEBTB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-CMs9G6mu64T8dkV4jwLmmiXvjMjUf5A',
    appId: '1:993398968251:android:2fedba9d1210debe0dbe9e',
    messagingSenderId: '993398968251',
    projectId: 'flutter-firebase-calenda-69514',
    storageBucket: 'flutter-firebase-calenda-69514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3NPLzz9wc_-p-DncYgJTQRK7wl4GsB7Q',
    appId: '1:993398968251:ios:423bd94e12b8f1620dbe9e',
    messagingSenderId: '993398968251',
    projectId: 'flutter-firebase-calenda-69514',
    storageBucket: 'flutter-firebase-calenda-69514.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3NPLzz9wc_-p-DncYgJTQRK7wl4GsB7Q',
    appId: '1:993398968251:ios:423bd94e12b8f1620dbe9e',
    messagingSenderId: '993398968251',
    projectId: 'flutter-firebase-calenda-69514',
    storageBucket: 'flutter-firebase-calenda-69514.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8LZZcnm071RcMjcgIagPwcgiwF1eP_Hg',
    appId: '1:993398968251:web:ec181d14da37308f0dbe9e',
    messagingSenderId: '993398968251',
    projectId: 'flutter-firebase-calenda-69514',
    authDomain: 'flutter-firebase-calenda-69514.firebaseapp.com',
    storageBucket: 'flutter-firebase-calenda-69514.firebasestorage.app',
    measurementId: 'G-86DLE7FLTY',
  );
}
